### ISSUE TITLE
Contrainte avec la refonte de la BD

### ISSUE THREAD

**Issue by KillianCARRAT** [KillianCARRAT/PROJET_FI#10]
1 Une salle ne peut pas être réservée plusieure fois au même moment
2 Il doit y avoir suffisamment de places en loges pour tous les artistes
3 Deux concerts d’un même groupe ne peuvent pas avoir lieu en même temps
4 Deux preparation de concert ne peuvent pas avoir lieu en même temps
5 La durée et préparation d’un concert est compris entre 0 et 24h
6 Le nombre de place du restaurants doit être supérieur ou égal au nombre de personnes dans le groupe + techniciens
7 Le nombre de place de l’hotels doit être supérieur ou égal au nombre de personnes dans le groupe + techniciens

**Comment by DanCoquerant** [comment]
TESTER VOS TRIGGERS ET CONTRAINTE AVANT DE PULL REQUEST

**Comment by moucmoi** [comment]
je fais la contrainte 1

**Comment by KillianCARRAT** [comment]
Je prend la contrainte 4

**Comment by Marin-univ** [comment]
je fait la contrainte 2

**Comment by DanCoquerant** [comment]
Je prend la contrainte 3 et 4

**Comment by manglij** [comment]
je vais faire la contrainte 6

**Comment by moucmoi** [comment]
je fais la contrainte 7

**Comment by moucmoi** [comment]
il nous manque la contrainte 4 dans la branche bd+faire les before update sur tout les trigger

**Comment by DanCoquerant** [comment]
Sauf changement de BD les trigger sont vérifier et terminer (avec tous un update)
