### ISSUE TITLE
Contraintes SQL

### ISSUE THREAD

**Issue by KillianCARRAT** [KillianCARRAT/PROJET_FI#3]
1 Une salle ne peut pas être réservée plusieure fois au même moment
2 Il doit y avoir suffisamment de places en loges pour tous les artistes
3 Deux concerts d’un même groupe ne peuvent pas avoir lieu en même temps
4 Deux preparation de concert ne peuvent pas avoir lieu en même temps
5 La durée et préparation d’un concert est compris entre 0 et 24h
6 Le nombre de place des restaurants doit être supérieur ou égal au nombre de personnes dans le groupe + techniciens
7 Le nombre de place des hotels doit être supérieur ou égal au nombre de personnes dans le groupe + techniciens
8 Le nombre de place des véhicule doit être supérieur ou égal au nombre de personnes dans le groupe + techniciens
9 Le volume total des véhicule doit être supérieur ou égal au volume total du matériels
10 Le nombre de place des parkings doivent être supérieur ou égal au nombre de véhicule

**Comment by moucmoi** [comment]
je fais la contrainte 1

**Comment by Marin-univ** [comment]
je fais la contraintes 2

**Comment by Marin-univ** [comment]
je fais la contrainte 4

**Comment by manglij** [comment]
je fais la contrainte 5

**Comment by manglij** [comment]
je fais la contrainte 6

**Comment by moucmoi** [comment]
la contrainte 1 est fini

**Comment by moucmoi** [comment]
je fais la contrainte 7

**Comment by KillianCARRAT** [comment]
On a pas fini mais comme on a du faire une refonte de la bd, on doit en modifier et supprimer certaine
